-- iter 4e: Risks declared inside a narrative + section subtitle for the
-- public view + stable per-narrative identifiers (D1, R1, ...) backed by
-- monotonic counters that survive deletes.
--
-- Five logical changes, ordered to keep the schema valid at every step:
--   1. Add subtitle + counter columns on project_narratives.
--   2. Add identifier on narrative_dependencies (nullable initially).
--   3. Backfill identifiers (D1..Dn per narrative) and align the counter.
--   4. Lock down identifier (NOT NULL + format CHECK + UNIQUE).
--   5. Create narrative_risks (with array_length CHECKs + GIN + RLS).
--   6. Create the two claim_next_*_identifier RPCs used by createX
--      mutations to atomically read-and-increment the counter.

-- ============================================================================
-- 1. project_narratives: section subtitle + auto-gen counters
-- ============================================================================

ALTER TABLE project_narratives
  ADD COLUMN risks_section_subtitle TEXT,
  ADD COLUMN next_risk_id INT NOT NULL DEFAULT 1,
  ADD COLUMN next_dependency_id INT NOT NULL DEFAULT 1;

COMMENT ON COLUMN project_narratives.risks_section_subtitle IS
  'Optional subtitle rendered under the "Riesgos del proyecto" heading in the public view. NULL = heading only.';

COMMENT ON COLUMN project_narratives.next_risk_id IS
  'Monotonic counter consumed by claim_next_risk_identifier() to assign R1, R2, ... Never decreases — guarantees identifiers are stable post-creation and never reused after a delete.';

COMMENT ON COLUMN project_narratives.next_dependency_id IS
  'Same role as next_risk_id but for narrative_dependencies (D1, D2, ...).';

-- ============================================================================
-- 2. narrative_dependencies: identifier column (still nullable here)
-- ============================================================================

ALTER TABLE narrative_dependencies
  ADD COLUMN identifier TEXT;

-- ============================================================================
-- 3. Backfill: assign D1..Dn per narrative, then align next_dependency_id
-- ============================================================================

WITH numbered AS (
  SELECT
    id,
    'D' || ROW_NUMBER() OVER (
      PARTITION BY narrative_id
      ORDER BY order_index, created_at
    ) AS new_id
  FROM narrative_dependencies
)
UPDATE narrative_dependencies d
SET identifier = n.new_id
FROM numbered n
WHERE d.id = n.id;

-- After backfill, set the counter so the next createDependency assigns
-- D(n+1), not D1. COALESCE handles narratives with zero dependencies.
UPDATE project_narratives n
SET next_dependency_id = COALESCE((
  SELECT MAX(SUBSTRING(d.identifier FROM 2)::INT) + 1
  FROM narrative_dependencies d
  WHERE d.narrative_id = n.id
), 1);

-- ============================================================================
-- 4. Lock down narrative_dependencies.identifier
-- ============================================================================

ALTER TABLE narrative_dependencies
  ALTER COLUMN identifier SET NOT NULL,
  ADD CONSTRAINT narrative_dependencies_identifier_format
    CHECK (identifier ~ '^D\d+$'),
  ADD CONSTRAINT narrative_dependencies_identifier_unique
    UNIQUE (narrative_id, identifier);

COMMENT ON COLUMN narrative_dependencies.identifier IS
  'Stable per-narrative ID (D1, D2, ...). Auto-generated by claim_next_dependency_identifier(); immutable post-creation. The counter never decreases so deletes do not reuse identifiers.';

-- ============================================================================
-- 5. narrative_risks
-- ============================================================================

CREATE TABLE narrative_risks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  narrative_id UUID NOT NULL
    REFERENCES project_narratives(id) ON DELETE CASCADE,
  -- Stable per-narrative identifier (R1, R2, ...). Auto-generated by
  -- claim_next_risk_identifier(); immutable post-creation.
  identifier TEXT NOT NULL CHECK (identifier ~ '^R\d+$'),
  title TEXT NOT NULL,
  description TEXT,
  severity TEXT NOT NULL DEFAULT 'medium'
    CHECK (severity IN ('low', 'medium', 'high')),
  -- Bullets. By design, a risk without an impact AND a mitigation does
  -- not exist — the structural floor is at least one element each. The
  -- UI additionally rejects empty trimmed strings before persisting.
  impacts TEXT[] NOT NULL DEFAULT '{}',
  mitigations TEXT[] NOT NULL DEFAULT '{}',
  -- UUID array referencing narrative_dependencies(id). Postgres can't FK
  -- an array element, so dangling refs (after a dep delete) are filtered
  -- in the renderer rather than enforced by the schema. See CLAUDE.md
  -- "related_dependency_ids" decision.
  related_dependency_ids UUID[] NOT NULL DEFAULT '{}',
  order_index INT NOT NULL,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- array_length(empty_array, 1) returns NULL, and `NULL >= 1` is NULL
  -- (not TRUE), so empty arrays fail this check by construction. The
  -- DEFAULT '{}' would also fail an INSERT that doesn't override it —
  -- callers must provide at least one element (the UI seeds with [''])
  CONSTRAINT narrative_risks_impacts_min
    CHECK (array_length(impacts, 1) >= 1),
  CONSTRAINT narrative_risks_mitigations_min
    CHECK (array_length(mitigations, 1) >= 1),
  UNIQUE (narrative_id, identifier)
);

CREATE INDEX narrative_risks_narrative_id_order_idx
  ON narrative_risks(narrative_id, order_index);

-- "Which risks reference this dependency?" stays fast as the
-- related_dependency_ids arrays grow. Same role as the equivalent GIN
-- on narrative_dependencies.provider_jira_issue_keys / narrative_workstreams.jira_issue_keys.
CREATE INDEX narrative_risks_related_deps_gin_idx
  ON narrative_risks USING GIN (related_dependency_ids);

CREATE TRIGGER narrative_risks_set_updated_at
  BEFORE UPDATE ON narrative_risks
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

COMMENT ON TABLE narrative_risks IS
  'Risks declared in a narrative. Cannot exist without at least one impact and one mitigation — enforced both in UI (non-empty trimmed strings) and via array_length CHECKs (structural floor).';

-- ============================================================================
-- 6. RPCs: atomic identifier claiming
-- ============================================================================
-- Each function increments the per-narrative counter and returns the
-- previous value formatted with the right prefix. RETURNING reads the
-- post-UPDATE row, so we subtract 1 to recover the value the caller
-- should use. Concurrent calls serialize via the row-level lock the
-- UPDATE takes — no race window.

CREATE OR REPLACE FUNCTION claim_next_risk_identifier(p_narrative_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  v_used INT;
BEGIN
  UPDATE project_narratives
  SET next_risk_id = next_risk_id + 1
  WHERE id = p_narrative_id
  RETURNING (next_risk_id - 1) INTO v_used;

  IF v_used IS NULL THEN
    RAISE EXCEPTION 'narrative % not found', p_narrative_id;
  END IF;

  RETURN 'R' || v_used;
END;
$$;

CREATE OR REPLACE FUNCTION claim_next_dependency_identifier(p_narrative_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  v_used INT;
BEGIN
  UPDATE project_narratives
  SET next_dependency_id = next_dependency_id + 1
  WHERE id = p_narrative_id
  RETURNING (next_dependency_id - 1) INTO v_used;

  IF v_used IS NULL THEN
    RAISE EXCEPTION 'narrative % not found', p_narrative_id;
  END IF;

  RETURN 'D' || v_used;
END;
$$;

GRANT EXECUTE ON FUNCTION claim_next_risk_identifier(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION claim_next_dependency_identifier(UUID) TO service_role;

-- ============================================================================
-- 7. Row Level Security
-- ============================================================================

ALTER TABLE narrative_risks ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_read ON narrative_risks
  FOR SELECT TO anon, authenticated USING (TRUE);
