-- =====================================================================
-- Initial schema for the Jira executive dashboard.
--
-- Tables: projects, issues, issue_links, sync_runs
--
-- Conventions:
--   * Ids that mirror Jira ids are stored as TEXT (Jira ids are strings;
--     do not coerce to numeric).
--   * created_at / updated_at on every table; updated_at is auto-maintained
--     by the moddatetime extension.
--   * `raw` jsonb columns store the original Jira response so we don't
--     lose data we have not modeled. RULE: never query `raw` from the UI
--     directly. If a field becomes recurrent, extract it to a typed
--     column in a follow-up migration.
--   * Hierarchy (subtask -> task, story -> epic) lives in issues.parent_id
--     (self-FK). We do NOT model a separate epic_id: in modern Jira
--     (team-managed and most company-managed projects), Atlassian unified
--     hierarchy under the standard `parent` field. Legacy projects using
--     the deprecated Epic Link customfield are out of scope.
--   * issue_links is for non-hierarchical relationships only (blocks,
--     relates to, duplicates, ...).
--
-- RLS for this iteration:
--   read-open for anon, write-closed (service role bypasses RLS for
--   writes from the sync code). Tighten when user auth lands.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS moddatetime;

-- ---------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------
CREATE TABLE projects (
  id                 TEXT PRIMARY KEY,
  key                TEXT NOT NULL UNIQUE,
  name               TEXT NOT NULL,
  lead_account_id    TEXT,
  lead_display_name  TEXT,
  raw                JSONB,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_synced_at     TIMESTAMPTZ
);

COMMENT ON COLUMN projects.raw IS
  'Original Jira response. Do NOT query from UI; if a field becomes recurrent, extract it to a typed column in a follow-up migration.';

CREATE TRIGGER projects_set_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ---------------------------------------------------------------------
-- issues
-- ---------------------------------------------------------------------
CREATE TABLE issues (
  id                     TEXT PRIMARY KEY,
  key                    TEXT NOT NULL UNIQUE,
  project_id             TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  summary                TEXT NOT NULL,
  issue_type             TEXT NOT NULL,
  status_name            TEXT NOT NULL,
  status_category        TEXT NOT NULL CHECK (status_category IN ('To Do', 'In Progress', 'Done')),
  assignee_account_id    TEXT,
  assignee_display_name  TEXT,
  priority               TEXT,
  parent_id              TEXT REFERENCES issues(id) ON DELETE SET NULL,
  due_date               DATE,
  created_at_jira        TIMESTAMPTZ,
  updated_at_jira        TIMESTAMPTZ,
  raw                    JSONB,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  synced_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN issues.parent_id IS
  'Self-FK. In modern Jira the standard `parent` field unifies subtask->task and story->epic; issue_type distinguishes the role.';
COMMENT ON COLUMN issues.raw IS
  'Original Jira response. Do NOT query from UI; if a field becomes recurrent, extract it to a typed column.';

CREATE INDEX issues_project_id_idx      ON issues(project_id);
CREATE INDEX issues_updated_at_jira_idx ON issues(updated_at_jira DESC);
CREATE INDEX issues_status_category_idx ON issues(status_category);
CREATE INDEX issues_parent_id_idx       ON issues(parent_id) WHERE parent_id IS NOT NULL;

CREATE TRIGGER issues_set_updated_at
  BEFORE UPDATE ON issues
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ---------------------------------------------------------------------
-- issue_links
-- ---------------------------------------------------------------------
CREATE TABLE issue_links (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_issue_id   TEXT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  target_issue_id   TEXT REFERENCES issues(id) ON DELETE SET NULL,
  target_issue_key  TEXT NOT NULL,
  link_type         TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT issue_links_unique UNIQUE (source_issue_id, target_issue_key, link_type)
);

COMMENT ON TABLE issue_links IS
  'Non-hierarchical issue relationships (blocks, relates to, duplicates, ...). Hierarchy lives in issues.parent_id.';
COMMENT ON COLUMN issue_links.target_issue_key IS
  'Issue key of the target. Always set; FK target_issue_id is nullable because the target may be in a project we have not synced yet (e.g., outside JIRA_PROJECT_KEYS). Backfill the FK when the target is later synced.';

CREATE INDEX issue_links_target_idx ON issue_links(target_issue_id) WHERE target_issue_id IS NOT NULL;

CREATE TRIGGER issue_links_set_updated_at
  BEFORE UPDATE ON issue_links
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ---------------------------------------------------------------------
-- sync_runs
-- ---------------------------------------------------------------------
CREATE TABLE sync_runs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at     TIMESTAMPTZ,
  status          TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed')),
  sync_type       TEXT NOT NULL CHECK (sync_type IN ('full', 'incremental')),
  project_key     TEXT,
  issues_created  INT NOT NULL DEFAULT 0,
  issues_updated  INT NOT NULL DEFAULT 0,
  issues_deleted  INT NOT NULL DEFAULT 0,
  links_skipped   INT NOT NULL DEFAULT 0,
  error_message   TEXT,
  jql_used        TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN sync_runs.project_key IS
  'NULL = run covered all configured projects; otherwise the specific project key. Used to compute incremental watermarks per project.';

CREATE INDEX sync_runs_status_idx      ON sync_runs(status);
CREATE INDEX sync_runs_project_key_idx ON sync_runs(project_key);
CREATE INDEX sync_runs_finished_at_idx ON sync_runs(finished_at DESC) WHERE status = 'success';

CREATE TRIGGER sync_runs_set_updated_at
  BEFORE UPDATE ON sync_runs
  FOR EACH ROW EXECUTE FUNCTION moddatetime(updated_at);

-- ---------------------------------------------------------------------
-- Row Level Security
--   This iteration ships read-only to viewers. The service role bypasses
--   RLS automatically and is used by the sync code for writes.
-- ---------------------------------------------------------------------
ALTER TABLE projects    ENABLE ROW LEVEL SECURITY;
ALTER TABLE issues      ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_runs   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon read projects"    ON projects    FOR SELECT TO anon USING (true);
CREATE POLICY "anon read issues"      ON issues      FOR SELECT TO anon USING (true);
CREATE POLICY "anon read issue_links" ON issue_links FOR SELECT TO anon USING (true);
CREATE POLICY "anon read sync_runs"   ON sync_runs   FOR SELECT TO anon USING (true);
